//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_RptDizel
    {
        public string fldDizel_No { get; set; }
        public string fldTrainMabda { get; set; }
        public string fldTrainMaghsad { get; set; }
        public Nullable<decimal> fldBarKhales { get; set; }
        public Nullable<decimal> fldBarNakhales { get; set; }
        public Nullable<decimal> fldMasafat { get; set; }
        public Nullable<decimal> fldTonNakhales { get; set; }
        public int malekid { get; set; }
        public int dizelid { get; set; }
        public string fldWagon_No { get; set; }
        public string fldIsMade12 { get; set; }
        public int MinTarikhBar { get; set; }
        public string fldBarnameId { get; set; }
        public string fldSeri { get; set; }
        public string fldNoeBar { get; set; }
    }
}
